# Generated by Django 4.2.2 on 2023-06-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0003_food_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='special_cal',
            field=models.IntegerField(null=True),
        ),
    ]
