# Generated by Django 4.2.2 on 2023-06-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0004_food_special_cal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
