# Generated by Django 4.2.2 on 2023-08-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_foods', '0005_alter_food_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='special_cal',
        ),
        migrations.RemoveField(
            model_name='food',
            name='special_price',
        ),
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='food',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
