# Generated by Django 4.2.2 on 2023-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], max_length=10)),
                ('weight', models.IntegerField()),
                ('high', models.IntegerField()),
                ('age', models.IntegerField()),
                ('dateinfo', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
